### ISSUE TITLE
Validate AbstractAnnotatedAlgorithm

### ISSUE THREAD

**Issue by htulipe** [52North/WPS#164]
Currently, if no method is tagged `@Execute` in a class extending `AbstractAnnotatedAlgorithm`, the program will fail with a `NullPointerException` at execution time (see the [line of code](https://github.com/52North/WPS/blob/dev/52n-wps-algorithm/src/main/java/org/n52/wps/server/AbstractAnnotatedAlgorithm.java#L54)). It would be nice for this to get validated when algorithm is loaded instead.

Cheers

**Comment by nuest** [comment]
+1

Would you be willing to create a pull request (including unit test) for that?

**Comment by htulipe** [comment]
Yes sure, I will try to find time.

**Comment by nuest** [comment]
Before you invest too much work: Generally we require contributors to sign a CLA - which sadly requires to send around ink on dead trees, but that's how the law is. The reason for this is that the 52N WPS is "managed code", so that we can make sure the project will be running smoothly even in many years time.

Find all information here: http://52north.org/about/licensing/cla-guidelines

If this is not an option for you, then we can see if the contribution is small enough to be accepted anyway.

**Comment by htulipe** [comment]
Okay thanks forthe heads up, I will take a look

**Comment by tkunicki** [comment]
feel free to shoot me Q's if needed (original author)

**Comment by htulipe** [comment]
OK @tkunicki, I appreciate.

**Comment by tkunicki** [comment]
@htulipe The existing implementation throws `RuntimeException` to signal error conditions.  You can just check for a `null` assignment to `this.executeMethodBinding` [here]( https://github.com/52North/WPS/blob/dev/52n-wps-algorithm/src/main/java/org/n52/wps/algorithm/annotation/AnnotatedAlgorithmIntrospector.java#L183) and throw a `RuntimeException` and it will handled consistently with other parsing errors.

**Comment by htulipe** [comment]
The PR is available at #165, thanks @tkunicki for the help.
